name: Comment

on:
  workflow_run:
    workflows: ['Upload data', 'Markdown Link Check']
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Download PR test coverage report
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: 'Unzip artifact'
        run: unzip ${{ github.workspace }}/artifact.zip
      - name: 'Comment on PR'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            const issue_number = Number(fs.readFileSync('./pr_number'));
            const artifactString = fs.readFileSync('./artifact.txt').toString().trimEnd();
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `${artifactString}`
            });
