name: Upload data

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - id: pr_number
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        mkdir -p ./pr
        echo $PR_NUMBER > pr_number
        echo Thanks for the PR $PR_NUMBER > artifact.txt
        echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
    - id: attach
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: |
          pr_number
          artifact.txt
 
