name: Test scan

on:
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        id: scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://example.org'
          cmd_options: '-a -T 1'
      - name: Get artifact link
        run:  |
          echo 'Artifact URL is ${{ steps.scan.outputs.artifact-url }}'
          echo '${{ steps.scan.outputs.artifact-url }}' >> $GITHUB_STEP_SUMMARY
